# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-2204
    env:
      ImageOS: ubuntu22

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.2
      with:
        elixir-version: '1.18.2' # [Required] Define the Elixir version
        otp-version: '27'       # [Required] Define the Erlang/OTP version
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
